### ISSUE TITLE
Feature request: Add a flag to obtain the version

### ISSUE THREAD

**Issue by carrodher** [bitnami-labs/readme-generator-for-helm#26]
At this moment there is not any flag to obtain the version of the tool I am running
```console
$ readme-generator -h
Usage: readme-generator [options]

Options:
  -v, --values <path>    Path to the values.yaml file
  -r, --readme <path>    Path to the README.md file
  -c, --config <path>    Path to the config file
  -m, --metadata <path>  Path for the metadata output file
  -h, --help             display help for command
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting it. 
  @miguelaeh Could you take a look to it ?

**Comment by miguelaeh** [comment]
Hi @carrodher ,
That's true. We will try to add it.
In the meanwhile take into account that the version used will be the one in the repository you cloned, since the installation will create a symlink to the repo path.
You can check there the `package.json` to see the version.
