### ISSUE TITLE
After each section in generated Parameters section there are two new blank lines instead of one

### ISSUE THREAD

**Issue by jakuboskera** [bitnami-labs/readme-generator-for-helm#50]
I am using [markdownlint](https://github.com/markdownlint/markdownlint), which lint all Markdown files according these [Markdown rules](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md) - including README.md files in Helm Charts.

**Describe the bug**
When readme-generator-for-helm runs, it generates Parameters section where after each section it includes two blank new lines that goes against this markdown rule [MD012 - Multiple consecutive blank lines](
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md012---multiple-consecutive-blank-lines). There should be only one new line after each section.

Currently it is a problem, because everytime Parameters section is generated, markdownlint says that this rule is not met because of that blank new lines.

**Expected behavior**
It generates only one blank new line after each section in Parameters section and if this section is last section in Parameters section it won't add any blank new lines.

**Comment by fmulero** [comment]
Thanks  @jakuboskera sorry for my late response. This issue should be resolved on the [2.5.0 release](https://github.com/bitnami-labs/readme-generator-for-helm/releases/tag/2.5.0)
