### ISSUE TITLE
Comment-only parameters are missing in the schema

### ISSUE THREAD

**Issue by fdlk** [bitnami-labs/readme-generator-for-helm#54]
I have a chart with default values.yaml that requires some values to be filled in when the chart is installed.
I think this use case is supported when I add `@param` lines without a value in `values.yaml`, e.g.

```
foo:
## @param foo.bar This parameter has a default value
  bar: "default"
## @param foo.baz [string] This is a required parameter that must be filled in at deploy time
```

When I generate a readme, both parameters are described. But when I generate a schema, only parameter bar makes it to the schema. Which is a pity, cause it's parameter baz that the user has to fill in and that is the most important one to validate.

**Comment by fmulero** [comment]
Thanks Fleur. Interesting use case, to be honest I've never taken into account required parameters in this way.

**Comment by fmulero** [comment]
Hi @fdlk, Sorry for my very late response.

I think this case is covered in version [2.6.0](https://github.com/bitnami-labs/readme-generator-for-helm/releases/tag/2.6.0). Could you give it a glance?

**Comment by fdlk** [comment]
Definitely will, thanks!!
