### ISSUE TITLE
Add support for non-empty array default values in the Readme

### ISSUE THREAD

**Issue by migruiz4** [bitnami-labs/readme-generator-for-helm#6]
Related to https://github.com/bitnami/charts/pull/7007.

The Readme-generator does not have support to include in the README the Arrays default values when needed. For example, the field `master.disableCommands` in the Redis chart, appears with default value `[]`, when it should be `[FLUSHDB, FLUSHALL]`.

I consider this information not trivial, and therefore should be included in the Readme generator.

As a suggestion, we could add a flag similar to `@skip` or `[array]`, that replaced the default value with a message recommending to `Check the values.yaml` when the array is too big to be displayed in the Readme table.

**Comment by miguelaeh** [comment]
I agree the arrays should not be set as empty by default. This was a change to avoid adding too long data as the default value.
