### ISSUE TITLE
Add npm i to binary creation doc

### ISSUE THREAD

**Issue by pleymor** [bitnami-labs/readme-generator-for-helm#64]
The documentation to create a unique binary does not work as is, it needs `npm install` as well:

## Single Binary

Execute the following commands to create a single executable binary for the tool:

```sh
git clone https://github.com/bitnami-labs/readme-generator-for-helm
cd ./readme-generator-for-helm
npm install
npm install -g pkg
pkg . -o readme-generator-for-helm
```

Otherwise it will create a crashing binary ^^

**Comment by fmulero** [comment]
Thanks a lot @pleymor for the suggestion. Please feel free to open a PR with your proposal, we will be happy to review it.
